### ISSUE TITLE
Stuttering sound

### ISSUE THREAD

**Issue by bibendovsky** [bibendovsky/bstone#24]

**Comment by bibendovsky** [comment]
Fix callback or thread solution.

**Comment by bibendovsky** [comment]
Fixed by optimizing callback solution (a8a6068d76473d12c9e0d659598f3234e870625e, 0736bf582bd85b4cedca1ffb6508eb52a544a60e, 968ae2e01081bb55b7642d37a10181d6c832a279, 527997d84df234307789775c4f8cc49986cb4558).

**Comment by Irv1n3** [comment]
Hi, it seems I still have some weird stuttering sound at the end of an "use" action (I don't know if it's related to the original issue here).

I've recorded a video (I can't upload it on github directly): https://dl.dropboxusercontent.com/u/15023930/Stuttering%20open%20key.avi

I don't really know if the issue is related to the port, the original game or even if it's expected but it's getting irritating very fast.

Thanks for your works so far :)

**Comment by bibendovsky** [comment]
Thanks for info. Created a new issue (#39) for the problem.
