### ISSUE TITLE
Some Capture Issues  !!

### ISSUE THREAD

**Issue by TP555** [bibendovsky/bstone#279]
Hi

it gives some problems with the Capture , MSI Afterburner does stop the FPS Capture on a Screen , which is complette Static  (No Moves) , that does stop or Freeze the Recording In OBS Studio , OBS Studio means , there is no Game for Capture at this momment , but not MSI Afterburner is the problem , it does just show the Issue , Reshade does to stop the Capture , see the FPS and Frametimes will froze , when the Screen is complette Static. , same as MSI Afterburner , Reshade cause not this problem.

https://www.youtube.com/watch?v=SKCcpAiELqE
see at the Intro , and at 1:12 the Text Box will not show in the Capture from OBS , but the Box was there in my Gameplay.

And i have find out , your Port use OpenGL32.dll , and D3D9.dll , is mayby here a conflict , why the Capture Stops at statc Screen  , and is a problem for OBS Studio  ?

**Comment by bibendovsky** [comment]
> it gives some problems with the Capture , MSI Afterburner does stop the FPS Capture on a Screen , which is complette Static (No Moves) , that does stop or Freeze the Recording In OBS Studio

Does not OBS Studio enough to capture the output? Why to use MSI Afterburner?

> see at the Intro , and at 1:12 the Text Box will not show in the Capture from OBS , but the Box was there in my Gameplay.

Tested with OBS Studio v25.0.8 (without MSI Afterburner and without ReShader) - works fine.

> And i have find out , your Port use OpenGL32.dll , and D3D9.dll , is mayby here a conflict , why the Capture Stops at statc Screen , and is a problem for OBS Studio ?

The port does not use both API simultaneously.
Direct3D API may be used by SDL if software renderer selected.
Otherwise it is OpenGL (2.0, 3.2 core or ES 2.0).

It is possible a probing of available renderer may cause the issues. Try to set manually appropriate renderer (except auto-detect) in the menu.
