### ISSUE TITLE
Weapons sound differences

### ISSUE THREAD

**Issue by Irv1n3** [bibendovsky/bstone#283]
Hi again, I'm adding to the ticket a video of the Slow Fire Protector sound with the version 1.2.2 and 1.2.5. 
You can clearly notice the difference, and I know there are some changes on the audio part with the 1.2.4 but it doesn't sound better in my opinion, the sound is far less clear now.

Is this result expected? If yes, is it possible to have a setting to keep the old "system"?
Thanks
[Pistol sound.zip](https://github.com/bibendovsky/bstone/files/4767690/Pistol.sound.zip)

**Comment by bibendovsky** [comment]
### Short answer
Yes, it's correct.
Old low-pass filter did not cut off higher frequencies.


### Explanation

Game's audio data encoded with three methods:
1) Sequence of commands for AdLib synthesizer
2) Sequence of commands for PC Speaker
3) Digitized audio samples in PCM representation

Mentioned above Slow Fire Protector sound encoded in PCM.

All PCM sounds in the game are sampled at `7000 Hz`.
Such rate [preservs](http://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem) frequences from `0 Hz` to `3500 Hz`.
System audio mixer usually operates on much higher rates (`44100 Hz`, `48000 Hz` or higher).
So audio data should be [upsampled](http://en.wikipedia.org/wiki/Upsampling) first before sending it to the system mixer.

Upsamling process includes interpolation and filtering.
The task of the filter is to cut off frequencies introduced by interpolation which were not exist in original audio data.

In our case "the sound is far less clear now" because new filter cuts off frequences above `3500 Hz`.
The more "clear" sound you heard in older versions was those additional higher frequences introduced by interpolation and almost bypassed by the old low-pass filter.

You may extract audio data (`--extract_sfx dir`) an try it to play in the player. You will also hear "muffled" sound.
(The file name of Slow Fire Protector is `sfx_00000024.wav`.)


![bstone_sfx_24_pcm_u8_48khz_mono_old_lpf](https://user-images.githubusercontent.com/1597301/84491505-55619680-acad-11ea-9e55-d92080a210de.png)
A spectrogram for old low-pass filter of "Slow Fire Protector" sound upsampled to `48000 Hz`.

![bstone_sfx_24_pcm_u8_48khz_mono_new_lpf_80](https://user-images.githubusercontent.com/1597301/84491534-5bf00e00-acad-11ea-9747-bbc4f5651ba2.png)
A spectrogram for new low-pass filter of "Slow Fire Protector" sound upsampled to `48000 Hz`.


### Options

It's possible to add command-line / menu option, for example, to turn off or on the low-pass filter.
Maybe additional option to control the order of the low-pass filter.

**Comment by XxMiltenXx** [comment]
I'd also appreciate it if this was toggleable. Maybe between "Off", "Old" and "New" or maybe even more options.
Right now it doesn't sound good, as the Adlib sounds are all upsampled normally, but suddenly the PCMs are extremely affected by the LPF. Besides, even under DOS it wouldn't use such a strong LPF, it was sound-card dependant.

I also noticed something else: The volume for door sounds is very low, was something changed there or is that also due to the LPF?

**Comment by bibendovsky** [comment]
> Right now it doesn't sound good, as the Adlib sounds are all upsampled normally, but suddenly the PCMs are extremely affected by the LPF.

AdLib sounds are different story - they are *synthetized* by sound card or emulator like in our case, hence does not require any resampling.

> The volume for door sounds is very low, was something changed there or is that also due to the LPF?

Could be LPF. Mixing was slightly changed in v1.2.0.

**Comment by Irv1n3** [comment]
Thanks for the update, it's perfect!
