### ISSUE TITLE
Player Death - Red Pixelation Errors

### ISSUE THREAD

**Issue by sudobbq** [bibendovsky/bstone#469]
Problem Statement:
Upon player death - red pixelation ignores aspect ratio using software mode and doesn't pixelate in the three GL modes.
Resolution I'm using:
3840x2160 

Software
![image](https://github.com/bibendovsky/bstone/assets/6578375/ec9dfe05-f583-427a-bff4-5a3794116334)

GL 2.0, GL 3.2 CORE, GLES 2.0
![image](https://github.com/bibendovsky/bstone/assets/6578375/fb6436c2-72c4-432a-94f6-47a87669079a)
(I had to capture the second screenshot in windowed mode for the GL renderers, but the symptom is the same)

Using latest build supplied to me, today, after the informant death bug fix:
1_2_13-wip-0362a09835bfa80ef33d23b62285001e6c778372

**Comment by bibendovsky** [comment]
Fix for *software renderer*:
[bstone_windows_x64_v1_2_13-wip-b5b8798c7537bd78f4ad7c09d81c3be82e39d28f.zip](https://github.com/bibendovsky/bstone/files/13955393/bstone_windows_x64_v1_2_13-wip-b5b8798c7537bd78f4ad7c09d81c3be82e39d28f.zip)
[bstone_windows_x86_v1_2_13-wip-b5b8798c7537bd78f4ad7c09d81c3be82e39d28f.zip](https://github.com/bibendovsky/bstone/files/13955396/bstone_windows_x86_v1_2_13-wip-b5b8798c7537bd78f4ad7c09d81c3be82e39d28f.zip)

Added separate issue (#470) for 3D rendrer.

**Comment by bibendovsky** [comment]
Fix for *GL renderer* (also includes the fix for *software renderer*, and the fix for #467):
[bstone_windows_x64_v1_2_13-wip-296ebe1636ccce60071aed7edf8ce072ee3f80c2.zip](https://github.com/bibendovsky/bstone/files/13998346/bstone_windows_x64_v1_2_13-wip-296ebe1636ccce60071aed7edf8ce072ee3f80c2.zip)
[bstone_windows_x86_v1_2_13-wip-296ebe1636ccce60071aed7edf8ce072ee3f80c2.zip](https://github.com/bibendovsky/bstone/files/13998347/bstone_windows_x86_v1_2_13-wip-296ebe1636ccce60071aed7edf8ce072ee3f80c2.zip)

**Comment by bibendovsky** [comment]
Use option in the main menu (GAME OPTIONS => SWITCHES2 => VANILLA FX) to toggle between vanilla-like effect and the fade one.
Note, that the software renderer isgnores this option.

**Comment by bibendovsky** [comment]
Fixed in #471 and #472.
