### ISSUE TITLE
PS - Save Bug on Floor 11

### ISSUE THREAD

**Issue by rnveach** [bibendovsky/bstone#483]
I have a weird bug with Planet Strike on 1.2.12 that only started once I beat floor 10 and moved to 11.

The save opens up to the beginning of Floor 11, but any time I save in the level after loading this, I instantly get transported to the beginning and all the enemies respawn. If I save in the middle of gaining points, loading that save still shows the points increasing. It is like the game is saving only part of the data and using the original of the rest.

I ensured I didn't have my saves as read-only. If they are readonly the whole game would crash (which I think should have a better fix), and this doesn't explain how the score is still being saved.

I was using WIP 301ec4f6b8af154e7a39e52bc3a1520d7870b295 before, but the issue still persists when switching back to the released version on the same save. I reverted my saves to yesterday's (before touching the WIP) and redid floor 10 with only the release version, and it looks like the issue no longer appears on floor 11. I don't know if this is just because I used a WIP when I shouldn't have or if the WIP included new commits that could be "faulty" or .... I am reporting the issue just in case.

New commits in WIP since 1.2.12: https://github.com/bibendovsky/bstone/compare/v1.2.12...master

I also noticed when using the level selector with the faulty save and going back to level 10, it didn't show the map and acted like I never entered it (saying no map data, instead of showing the map) even though when entering it shows 100% clear.

Faulty Save: https://rveach.no-ip.org/bstone_ps_saved_game_0

**Comment by bibendovsky** [comment]
Fixed in 096da5cea9615eaac896ccfd59891fc55af0ac0e.
Note that it does not remedy already faulty saved games.

[bstone_windows_i686_v1_2_13-wip+096da5cea9615eaac896ccfd59891fc55af0ac0e.zip](https://github.com/bibendovsky/bstone/files/14894402/bstone_windows_i686_v1_2_13-wip%2B096da5cea9615eaac896ccfd59891fc55af0ac0e.zip)
[bstone_windows_x86_64_v1_2_13-wip+096da5cea9615eaac896ccfd59891fc55af0ac0e.zip](https://github.com/bibendovsky/bstone/files/14894403/bstone_windows_x86_64_v1_2_13-wip%2B096da5cea9615eaac896ccfd59891fc55af0ac0e.zip)

**Comment by bibendovsky** [comment]
Feel free to re-open the issue if the problem persists.
