### ISSUE TITLE
Door becomes an open space, unable to interact or pass through

### ISSUE THREAD

**Issue by KUBA18i** [bibendovsky/bstone#49]
![20160807174111_1](https://cloud.githubusercontent.com/assets/20889223/17463646/b05226f4-5cca-11e6-901b-5850210d1c2a.jpg)
 Cannot pass through it, use key does nothing, projectiles can't pass through it either. First time it happened somewhere in E2L2, second time it happened at the door near the starting area in E4L1, and third time it happened here, rendering me unable to progress through the episode without resetting it. Debug mode does not seem to contain any cheats that would help me here (noclip or teleportation). I am not sure what causes the bug. I am using the 64-bit 1.1.7 version of the source port on a Windows 10 Home PC.

**Comment by bibendovsky** [comment]
Can you provide a saved game file with the issue?

**Comment by KUBA18i** [comment]
Yes. https://www.dropbox.com/s/nq00mfu3oscz16z/bstone_aog_full_saved_game_0?dl=0

**Comment by Sean-Der** [comment]
@bibendovsky here is another save file that demos it, the one provided before wasn't directly in front of the door. If you load without my patch you can't move through the door (it believes that there is a post_barrierobj in the way)

https://ufile.io/vri71

I can't find a way to generate a bad save file, but I believe this assert is all that is needed I have only seen this after a load. I assume this is because the save was generated while data is in flight (maybe?) 

If my PR isn't right happy to fix it up!

**Comment by Sean-Der** [comment]
Also @KUBA18i my fix works for your save file as well, there is invalid data in your save file (and my patch fixes it)

**Comment by bibendovsky** [comment]
Fixed in #88
